(function(){
 const navToggle=document.getElementById('navToggle'), nav=document.getElementById('mainNav');
 if(navToggle){navToggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');navToggle.setAttribute('aria-expanded',open);});}
 document.querySelectorAll('#mainNav a').forEach(a=>a.addEventListener('click',()=>nav&&nav.classList.remove('open')));
 function getLang(){return localStorage.getItem('cpg_lang')||'bg'}
 function setLanguage(lang){const dict=window.CPG_TRANSLATIONS&&window.CPG_TRANSLATIONS[lang];if(!dict)return;document.documentElement.lang=lang==='gr'?'el':lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(dict[k]!==undefined)el.textContent=dict[k]});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const k=el.dataset.i18nPlaceholder;if(dict[k]!==undefined)el.placeholder=dict[k]});document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem('cpg_lang',lang);}
 document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang))); setLanguage(getLang()); const mc=document.getElementById('mobileCall'); if(mc && window.CPG_CONFIG && CPG_CONFIG.phone){mc.href='tel:'+CPG_CONFIG.phone;}
 const form=document.getElementById('quoteForm');
 if(form){form.addEventListener('submit',async e=>{e.preventDefault();const status=document.getElementById('formStatus'), cfg=window.CPG_CONFIG||{};const data=Object.fromEntries(new FormData(form).entries());status.textContent='';
   if(cfg.formEndpoint){try{const r=await fetch(cfg.formEndpoint,{method:'POST',headers:{'Accept':'application/json','Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw new Error();form.reset();status.textContent='✓ Запитването е изпратено.';return}catch(err){status.textContent='Неуспешно изпращане. Моля, използвайте имейла за контакт.';return}}
   if(cfg.contactEmail){const subject=encodeURIComponent('CPG Design — ново запитване');const body=encodeURIComponent(`Име: ${data.name}\nИмейл: ${data.email}\nТелефон: ${data.phone||'-'}\nКатегория: ${data.category}\n\nСъобщение:\n${data.message}`);window.location.href=`mailto:${cfg.contactEmail}?subject=${subject}&body=${body}`;status.textContent='Ще се отвори вашият имейл клиент за изпращане на запитването.';return}
   status.textContent='Формата е готова. Добавете contactEmail или formEndpoint в config.js, за да получавате запитвания.';
 });}
})();

function buildGalleryPage({title,desc,files,folder,backText}){document.title=title+' | CPG Design';const grid=document.getElementById('galleryGrid');const items=files.map(f=>({src:folder+'/'+f,alt:title+' — CPG Design'}));items.forEach((item,i)=>{const b=document.createElement('button');b.className='gallery-item';b.type='button';b.innerHTML=`<img src="${item.src}" alt="${item.alt}" loading="lazy">`;b.addEventListener('click',()=>openLightbox(items,i));grid.appendChild(b)});const lb=document.createElement('div');lb.className='lightbox';lb.id='lightbox';lb.innerHTML='<button class="lb-close" aria-label="Close">×</button><button class="lb-prev" aria-label="Previous">‹</button><img><button class="lb-next" aria-label="Next">›</button>';document.body.appendChild(lb);let index=0;const img=lb.querySelector('img');function show(i){index=(i+items.length)%items.length;img.src=items[index].src;img.alt=items[index].alt;lb.classList.add('open');document.body.style.overflow='hidden'}function close(){lb.classList.remove('open');document.body.style.overflow=''}lb.querySelector('.lb-close').onclick=close;lb.querySelector('.lb-prev').onclick=()=>show(index-1);lb.querySelector('.lb-next').onclick=()=>show(index+1);lb.addEventListener('click',e=>{if(e.target===lb)close()});document.addEventListener('keydown',e=>{if(!lb.classList.contains('open'))return;if(e.key==='Escape')close();if(e.key==='ArrowLeft')show(index-1);if(e.key==='ArrowRight')show(index+1)});window.openLightbox=show;}
